### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by mcousillas6**
#### Change log:
* Updated code to match API and style changes.
* Updated eureka to version `2.0.0-beta.1` for swift 3 support.
* Implemented initWithCoder, now is needed.

### CODE REVIEW

**Comment by ghost** [comment]
Hello @mcousillas6,

I try to dowlload your code in Xcode 8 but it doesn't compile. I had the following errors

ld: warning: directory not found for option '-F../Carthage/Build/iOS'
ld: framework not found Eureka
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do you have any idea to correct this ?

Regards
Sébastien

**Comment by dernster** [comment]
@iLandes Did you run the `bin/setup` script after cloning/switching to this branch?

**Comment by ghost** [comment]
I do not  bin/setup

**Comment by dernster** [comment]
@iLandes Please try it and let me know. You can follow the instructions [here](https://github.com/EurekaCommunity/GenericPasswordRow/issues/1#issuecomment-277581554)

**Pull request merged**
