### PR TITLE
Typo fix and remove embedded swift libraries

### PR DESCRIPTION
**Pull request by nidegen**
Fixes a bug for App Store deployment as in [described here](https://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr)

### CODE REVIEW

**Comment by dernster** [comment]
thanks @nidegen !

**Comment by dernster** [comment]
@nidegen If I run the example project with this new setting I get this error:

```
dyld: Library not loaded: @rpath/libswiftSwiftOnoneSupport.dylib
  Referenced from: /Users/dernst/Library/Developer/Xcode/DerivedData/GenericPasswordRow-fpmsjmlksqqfftgrqxutbuuelynd/Build/Products/Debug-iphonesimulator/GenericPasswordRow.framework/GenericPasswordRow
  Reason: image not found
```

If I revert these new settings the project runs just fine. Any idea?

**Comment by nidegen** [comment]
let me look into it. not sure right now

**Comment by nidegen** [comment]
hmm seemed to work for me. clear derived data/clean build maybe?

**Comment by nidegen** [comment]
sorry, no it also breaks at runtime

**Comment by nidegen** [comment]
it worked on relase mode though.. seems to be some sort of optimization issue: https://stackoverflow.com/a/41134392

**Comment by dernster** [comment]
@nidegen Are you using carthage right?

What about installing this library using `carthage bootstrap --configuration Release` before making an archive?

If that works and you agree, I'm gonna revert this flag change

**Comment by nidegen** [comment]
agreed, undo it. i fixed a doc typo as well, make sure not to undo that;)

**Pull request merged**
